### ISSUE TITLE
drawbot download problem

### ISSUE THREAD

**Issue by typoman** [robofont-mechanic/mechanic-2#24]
Not sure if this is the right place to report this or the extenion repo?
```
Traceback (most recent call last):
  File "PyObjCTools/AppHelper.pyc", line 79, in scheduleCallWithDelay_
  File "PyObjCTools/AppHelper.pyc", line 97, in performCall
  File "../Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/extensionItem.py", line 182, in _remoteInstallCallback
    raise ExtensionRepoError(message)
mechanic2.mechanicTools.ExtensionRepoError: Could not download the extension zip file for: 'DrawBot'
```

**Comment by typemytype** [comment]
do you have the latest Mechanic? 
there should be a detailed error message in the [RoboFont log](https://robofont.com/documentation/how-tos/submitting-bug-reports/#console-logs)

cc @verbosus

**Comment by verbosus** [comment]
@typoman are you on the latest Mechanic? Anything popping up in the logs?

**Comment by gferreira** [comment]
I am getting this error too – not just with DrawBot but also with MarkyMark, ScaleFast, probably others.

in addition to the error message above, I also get this message in the log file:

```console
25/11/2019 12:24:49 >    ERROR > Mechanic >> Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://codeload.github.com/typemytype/drawBotRoboFontExtension/zip/master, NSErrorFailingURLKey=https://codeload.github.com/typemytype/drawBotRoboFontExtension/zip/master, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.}
```

the URLs are fine, I can download the zips by pasting them in the browser.

not sure if this is relevant, but I am using a 4Mbps internet connection.

thanks for looking into it!

**Comment by verbosus** [comment]
@gferreira can you help me reproduce this with some consistency? 

I can’t. I tried installing all these extensions just now and got no big problems. I did, however, try  to `time curl` the URL in the error above and my machine responded with:
```
real	0m10.864s
user	0m0.097s
sys	0m0.328s
```
Which is rather a lot, and would get killed by URLReader’s default 10 seconds timeout. I’m on a relatively fast connection, so I’m thinking Github is throttling the downloads somehow. 

One potential fix could be to increase the default timeout from 10 seconds to about 30 or so. Hell, we could even put it at 60 seconds, but either way we should also have a “cancel” button, which right now the UI doesn’t have.

What do you & @typemytype think?

**Comment by gferreira** [comment]
hello @verbosus,

here’s what I get for the same URL at 4Mbps:

```
gferreira:~ gferreira$ time curl https://codeload.github.com/typemytype/drawBotRoboFontExtension/zip/master > drawBotRoboFontExtension.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.1M    0 13.1M    0     0   176k      0 --:--:--  0:01:16 --:--:--  156k

real	1m16.390s
user	0m1.080s
sys	0m0.716s
```

🐇🐢

so, we should define a time limit which allows downloading the largest extensions in the slowest connections. I can make some more tests in the turtle end of the spectrum.

a *Cancel* button might indeed be needed if the time limit becomes too long. let’s try it without first :)

**Comment by typemytype** [comment]
what does the time out measure? the first ping connections: something is able to listen on the other side or the total amount of time for the zip download? 

and there is also a difference between [timeoutIntervalForResource ](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1408259-timeoutintervalforrequest?language=objc) and [timeoutIntervalForRequest](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1408259-timeoutintervalforrequest?language=objc)

the interval for a resource is as default 7 days :) and per request a time out is retried:

> Any upload or download tasks created by a background session are automatically retried if the original request fails due to a timeout. To configure how long an upload or download task should be allowed to be retried or transferred, use the timeoutIntervalForResource property.

**Comment by verbosus** [comment]
The timeout in URLReader is the total response including the initial connection, overriding NSURLSession’s defaults. So yeah, 10 seconds is way too low. I’ve already increased it to 120 seconds locally and I have been working on replacing the progress sheet with a little control that is non-modal and cancellable. PR coming soon.

**Comment by typoman** [comment]
sorry for the late reply. When I hit `download` drawbot nothing happens, but when I hit `check updates` here is the log I get:
```
Traceback (most recent call last):
​  File "PyObjCTools/AppHelper.pyc", line 79, in scheduleCallWithDelay_
  File "PyObjCTools/AppHelper.pyc", line 97, in performCall
  File "/Users/bahmaneslami/Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/extensionItem.py", line 182, in _remoteInstallCallback
    raise ExtensionRepoError(message)
mechanic2.mechanicTools.ExtensionRepoError: Could not download the extension zip file for: 'DrawBot'
Traceback (most recent call last):
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/vanillaBase.py", line 500, in action_
    self.callback(sender)
  File "/Users/bahmaneslami/Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/ui/controller.py", line 430, in checkForUpdatesCallback
    _checkForUpdatesCallback(True)
  File "/Users/bahmaneslami/Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/ui/controller.py", line 424, in _checkForUpdatesCallback
    self.checkForUpdates(installed)
  File "/Users/bahmaneslami/Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/ui/controller.py", line 346, in checkForUpdates
    item.checkForUpdates()
  File "/Users/bahmaneslami/Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/extensionItem.py", line 499, in checkForUpdates
    postEvent(EXTENSION_DID_CHECK_FOR_UPDATES_EVENT_KEY, item=self)
  File "lib/eventTools/eventManager.pyc", line 488, in postEvent
  File "lib/eventTools/eventManager.pyc", line 155, in postEvent_info_
  File "lib/eventTools/eventManager.pyc", line 129, in callObserver_withMethod_forEvent_withInfo_
  File "/Users/bahmaneslami/Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/ui/controller.py", line 288, in extensionDidCheckForUpdates
    self._progress.update()
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/defconAppKit/windows/progressWindow.py", line 29, in update
    self.w.progress.increment()
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/vanillaProgressBar.py", line 123, in increment
    NSRunLoop.mainRunLoop().runUntilDate_(NSDate.dateWithTimeIntervalSinceNow_(0.0001))
  File "PyObjCTools/AppHelper.pyc", line 79, in scheduleCallWithDelay_
  File "PyObjCTools/AppHelper.pyc", line 97, in performCall
  File "/Users/bahmaneslami/Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/extensionItem.py", line 182, in _remoteInstallCallback
    raise ExtensionRepoError(message)
mechanic2.mechanicTools.ExtensionRepoError: Could not download the extension zip file for: 'DrawBot'
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 95, in sendEvent_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/vanillaBase.py", line 500, in action_
    self.callback(sender)
  File "/Users/bahmaneslami/Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/ui/controller.py", line 430, in checkForUpdatesCallback
    _checkForUpdatesCallback(True)
  File "/Users/bahmaneslami/Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/ui/controller.py", line 424, in _checkForUpdatesCallback
    self.checkForUpdates(installed)
  File "/Users/bahmaneslami/Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/ui/controller.py", line 346, in checkForUpdates
    item.checkForUpdates()
  File "/Users/bahmaneslami/Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/extensionItem.py", line 499, in checkForUpdates
    postEvent(EXTENSION_DID_CHECK_FOR_UPDATES_EVENT_KEY, item=self)
  File "lib/eventTools/eventManager.pyc", line 488, in postEvent
  File "lib/eventTools/eventManager.pyc", line 155, in postEvent_info_
  File "lib/eventTools/eventManager.pyc", line 129, in callObserver_withMethod_forEvent_withInfo_
  File "/Users/bahmaneslami/Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/ui/controller.py", line 288, in extensionDidCheckForUpdates
    self._progress.update()
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/defconAppKit/windows/progressWindow.py", line 29, in update
    self.w.progress.increment()
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/vanillaProgressBar.py", line 123, in increment
    NSRunLoop.mainRunLoop().runUntilDate_(NSDate.dateWithTimeIntervalSinceNow_(0.0001))
  File "PyObjCTools/AppHelper.pyc", line 79, in scheduleCallWithDelay_
  File "PyObjCTools/AppHelper.pyc", line 97, in performCall
  File "/Users/bahmaneslami/Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/extensionItem.py", line 182, in _remoteInstallCallback
    raise ExtensionRepoError(message)
mechanic2.mechanicTools.ExtensionRepoError: Could not download the extension zip file for: 'DrawBot'
```
I have installed other extensions during this time and had no issue.

**Comment by gferreira** [comment]
this seems to have been fixed (thanks!), I get no timeout errors even with very large extensions.

can we close?

**Comment by verbosus** [comment]
Hang on a sec @gferreira I haven’t been able to actually commit any changes to Mechanic just yet. I have been working on a patch to increase URLReader’s timeout to a more reasonable value and to add a small bit of UI to cancel long running operations but had to break for the holidays. Hoping to get that PR wrapped up soon so we can close this. @typemytype can you assign the issue to me in the meantime?

**Comment by gferreira** [comment]
@verbosus great, thanks. let me know if you need any help with testing.

one idea to enhance the UX: add some indication while the files are being fetched, and/or disable the Install button for that extension.

**Comment by typemytype** [comment]
I guess this PR never happend... let me see how I can fix it from my side

**Comment by verbosus** [comment]
Oooopsie! The fix was to literally just increase the timeout in URLReader, which I did in the PR. I also filed https://github.com/robofont-mechanic/mechanic-2/issues/29 to track the download-canceling bit of UI I didn’t finish yet.

**Comment by typemytype** [comment]
thanks! the best 60 sec ever!
