### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by ori-bendor** [robofont-mechanic/mechanic-2#26]
I cannot install any extension from Mechanic 2.
For example, from robofont-3-py3.log:

11/04/2020 02:44:08 >    ERROR > Mechanic >> Could not find the extension: 'PangrammerHelper.roboFontExt'
11/04/2020 02:44:08 >   OUTPUT > ROBOFONT >> Traceback (most recent call last):
11/04/2020 02:44:08 >   OUTPUT > ROBOFONT >> File "PyObjCTools/AppHelper.pyc", line 79, in scheduleCallWithDelay_
11/04/2020 02:44:08 >   OUTPUT > ROBOFONT >> File "PyObjCTools/AppHelper.pyc", line 97, in performCall
11/04/2020 02:44:08 >   OUTPUT > ROBOFONT >> File "/Users/oribendor/Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/extensionItem.py", line 208, in _remoteInstallCallback
11/04/2020 02:44:08 >   OUTPUT > ROBOFONT >> raise ExtensionRepoError(message)
11/04/2020 02:44:08 >   OUTPUT > ROBOFONT >> mechanic2.mechanicTools
11/04/2020 02:44:08 >   OUTPUT > ROBOFONT >> .
11/04/2020 02:44:08 >   OUTPUT > ROBOFONT >> ExtensionRepoError
11/04/2020 02:44:08 >   OUTPUT > ROBOFONT >> :
11/04/2020 02:44:08 >   OUTPUT > ROBOFONT >> Could not find the extension: 'PangrammerHelper.roboFontExt'

**Comment by ori-bendor** [comment]
Forgot to add that I used to be able to install from Mechanic 2, but then it stopped working some time ago (at least a few weeks, possible a few months, I'm not sure).

**Comment by ori-bendor** [comment]
Oh, wait a minute.
I can install most extensions.
I just had a very bad luck with the few ones I tried to install recently.
In this case, for example, it's a file name issue: PangrammerHelper.roboFontExt vs Pangrammer Helper.roboFontExt (with or without a space).
